# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Mark Richardson
email: m.g.richardson@leeds.ac.uk
full_name: Mark Richardson
github_organization: MarkUoLeeds
keywords: dessert,sweet
license: Apachev2
package_name: baklava
package_short_description: A sweet recipe
template_profile: minimum
version: 0.1.0
